version: '3.9'
services:
  glpi_app:
    image: tauanslima/glpi:10.0.16
    container_name: glpi-10
    volumes:
      - glpi_config:/etc/glpi
      - glpi_documents:/var/lib/glpi/files/data-documents
      - glpi_plugins:/usr/share/glpi/plugins
      - glpi_marketplace:/usr/share/glpi/marketplace
      - glpi_files_plugins:/var/lib/glpi/files/_plugins
      - glpi_backup:/backup
    networks:
      - glpi
    ports:
      - 80:80

  glpidb:
    image: percona/percona-server:8.0
    container_name: db-glpi-10
    networks:
      - glpi
    volumes:
      - glpi_db_log:/var/log/mysql
      - glpi_db_lib:/var/lib/mysql
      - glpi_db_backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=SENHAROOT
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=SENHADATABASE
      - TZ=America/Sao_Paulo 

networks:
  glpi:
    driver: bridge   

volumes:
  glpi_config:
  glpi_documents:
  glpi_plugins:
  glpi_marketplace:
  glpi_files_plugins:
  glpi_backup:
  glpi_db_log:
  glpi_db_lib:
  glpi_db_backup:
